apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: burguerspace
spec:
  selector:
    app: api
  ports:
  - name: api
    port: 5000
    targetPort: 8080
    nodePort: 30479
  type: NodePort