apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: burguerspace
spec:
  selector:
    app: pgadmin
  ports:
  - name: pgadmin
    port: 5050
    targetPort: 80
    nodePort: 32349
  type: NodePort