apiVersion: v1
kind: Service
metadata:
  name: pgdb
  namespace: burguerspace
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30001
  type: NodePort